// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpc_user_query.proto

package user_query

import (
	context "context"
	user_domain "github.com/wuyazi/grpc_user_domain/user_domain"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserQueryClient is the client API for UserQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserQueryClient interface {
	InsertUser(ctx context.Context, in *user_domain.UserCreated, opts ...grpc.CallOption) (*UserResp, error)
	GetByUserId(ctx context.Context, in *GetByUserIdReq, opts ...grpc.CallOption) (*UserResp, error)
}

type userQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserQueryClient(cc grpc.ClientConnInterface) UserQueryClient {
	return &userQueryClient{cc}
}

func (c *userQueryClient) InsertUser(ctx context.Context, in *user_domain.UserCreated, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := c.cc.Invoke(ctx, "/user_query.userQuery/insertUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userQueryClient) GetByUserId(ctx context.Context, in *GetByUserIdReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := c.cc.Invoke(ctx, "/user_query.userQuery/getByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQueryServer is the server API for UserQuery service.
// All implementations must embed UnimplementedUserQueryServer
// for forward compatibility
type UserQueryServer interface {
	InsertUser(context.Context, *user_domain.UserCreated) (*UserResp, error)
	GetByUserId(context.Context, *GetByUserIdReq) (*UserResp, error)
	mustEmbedUnimplementedUserQueryServer()
}

// UnimplementedUserQueryServer must be embedded to have forward compatible implementations.
type UnimplementedUserQueryServer struct {
}

func (UnimplementedUserQueryServer) InsertUser(context.Context, *user_domain.UserCreated) (*UserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertUser not implemented")
}
func (UnimplementedUserQueryServer) GetByUserId(context.Context, *GetByUserIdReq) (*UserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserId not implemented")
}
func (UnimplementedUserQueryServer) mustEmbedUnimplementedUserQueryServer() {}

// UnsafeUserQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserQueryServer will
// result in compilation errors.
type UnsafeUserQueryServer interface {
	mustEmbedUnimplementedUserQueryServer()
}

func RegisterUserQueryServer(s grpc.ServiceRegistrar, srv UserQueryServer) {
	s.RegisterService(&UserQuery_ServiceDesc, srv)
}

func _UserQuery_InsertUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user_domain.UserCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServer).InsertUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_query.userQuery/insertUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServer).InsertUser(ctx, req.(*user_domain.UserCreated))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserQuery_GetByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServer).GetByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_query.userQuery/getByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServer).GetByUserId(ctx, req.(*GetByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserQuery_ServiceDesc is the grpc.ServiceDesc for UserQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_query.userQuery",
	HandlerType: (*UserQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "insertUser",
			Handler:    _UserQuery_InsertUser_Handler,
		},
		{
			MethodName: "getByUserId",
			Handler:    _UserQuery_GetByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_user_query.proto",
}
