// Code generated by goctl. DO NOT EDIT.
// Source: grpc_user_query.proto

package server

import (
	"context"

	"github.com/wuyazi/grpc_user_query/internal/logic"
	"github.com/wuyazi/grpc_user_query/internal/svc"
	"github.com/wuyazi/grpc_user_query/user_query"
)

type UserQueryServer struct {
	svcCtx *svc.ServiceContext
	user_query.UnimplementedUserQueryServer
}

func NewUserQueryServer(svcCtx *svc.ServiceContext) *UserQueryServer {
	return &UserQueryServer{
		svcCtx: svcCtx,
	}
}

// rpc insertUser(user_domain.UserCreated) returns(userResp);
func (s *UserQueryServer) GetByUserId(ctx context.Context, in *user_query.GetByUserIdReq) (*user_query.UserResp, error) {
	l := logic.NewGetByUserIdLogic(ctx, s.svcCtx)
	return l.GetByUserId(in)
}
